### ISSUE TITLE
Automate installation?

### ISSUE THREAD

**Issue by parsiya** [parsiya/eslinter#14]
It's possible to have a ~~script~~ ~~separate jar~~ few Gradle tasks that automates the installation of the extension.

* [x] Create the repository in #12.
* [x] Add it as a sub-module to eslint-burp.

The tasks need to do most of the steps in the current `Quickstart` section:

### gradlew clean

* [x] Delete the `eslint-security` and `release` directories..

### gradlew install

* [x] Get the `eslint-security` git submodule. Implemented in #12.
    * [x] `git submodule update --init --recursive --remote`.
* [x] Build the project via gradle.
    * [x] Run the `bigJar` Gradle task.
* [x] Navigate to eslint-security and run `npm install`.
    * [x] Change working directory to `$pwd`/`eslint-security`.
    * [x] Store this path.
    * [x] `npm install`.

### gradlew config

* [x] Read a command-line parameter. This will be the project path.
* [x] Check if `install` has been called by checking for the existence of `currentDir/eslint-security/node_modules`.

* [x] `beautified-javascript-path`: Path to store extracted JavaScript files.
    * `target/beautified`
* [x] `eslint-output-path`: Path to store ESLint results.
    * `target-linted`
* [x] `database-path`: Location of the target database.
    * `target/eslinter.sqlite`.

* [x] `eslint-command-path`: Path to the eslint command.
    * Point to the `eslint` command inside `currentDir/node_modules/.bin/`.
    * Customize it based on OS. Windows = `eslint.cmd`. Linux/Mac = `eslint`.
* [x] `jsbeautify-command-path`: Path to the js-beautify command.
    * Point to the `js-beautify` command inside `currentDir/node_modules/.bin/`.
    * Customize it based on OS. Windows = `js-beautify.cmd`. Linux/Mac = `js-beautify`.
* [x] `eslint-config-path`: Path to the ESLint configuration file.
    * Path to the config file inside `currentDir/eslint-security/configs/eslintrc-parsia.js`.
* [x] Store the config file in the `currentDir/release/config.json` directory. The extension can use it with #13.
* [x] Add it to the readme, replace the instructions, move the old quickstart to a page under docs and mention it.
